repos:
  - repo: local
    hooks:
      - id: swift-format
        name: swift-format
        entry: swift-format lint --strict
        language: system
        files: \.swift$
      - id: swiftlint
        name: swiftlint
        entry: swiftlint lint --strict
        language: system
        files: \.swift$
